[package]
name = "tomoz-python"
description = "Python bindings of Tomoz"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
publish = false

[lib]
name = "_tomoz"
crate-type = ["cdylib"]

[dependencies]
tomoz-codec = { workspace = true, features = ["parallel"] }
tomoz-archive.workspace = true
pyo3 = { workspace = true, features = ["extension-module"] }
numpy.workspace = true

[lints]
workspace = true
